dist: trusty
language: node_js
node_js:
  - "node"
  - "6"
  - "5"
  - "4"
env:
  global:
    # BROWSERSTACK_KEY="?"
    - secure: "JiMtpVAzHCPqXKBSFKMr3Nq+D1HbacekBRooiFN82pjqc88WXTDMYaEWdd5JVkXdAnvJOxWXBSngpzA7jVDsbxUe3iPkQIZOU5733+BQMVT1spqJUty2SDLMIgjpMAZU3Dai+SQ7iCOpNzdLlIHlg08mfEDqbS4hRX8OF1jY9nvJTON+OdDwznFhpfN2C9EuUwjau9F8owFisodSzURfe0ou6bvsuUcekPo+iGFHsnS4OiKQGdWrFclbXsbeEn9VGSaUMT0OfarW/sxhR/54NVGh0b6onrnYnhwORJ7bUcn4k9IhCuw3/TGM2nA38ec0CwEUmrC2JdD183Ta5xX6LOLi+QPIALsdbt0YGRrxMMicQSu72hIwjKdnOlNbs7ynZAWkK/I5ZCKs1JFH04sVGH9bD8hFTZTtzhL47KjHh0CWBHPgL1KDRPtXoOxLgZ9qrd1enwkL+VktQhJnd0Y7rGZhVjNb9bYL8LSfAFI6Qf9MPAAuj8S+gMnEtqpdNOtw/xr38N6l8Z5ShMTnv9qzmOWXsDj3EKaZLLlFiHMnxlzVIslD2wT2QgJejp6/JAZ+jICinZPvAeL1cYhurg0Qtk4r1qdfrDiUQtkiqjjiGzVmE9axuVaMmf9vdQFbX7TEBvf4wLpUa6K6CYBoBsIgY28dXyVW9mXII0+y5Nijl9M="
    - CXX=g++-4.8
matrix:
  include:
    - env: REFRACTIVE_BROWSER_TESTS=true
      node_js: "6"
before_script:
  - touch .env
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  browserstack:
    username: 'janneliuhtonen1'
    access_key:
      secure: "fuDiiHHYJkGQ8O0e1Di/o0rUWetM4CER3uNFtnm+ALwm/PfUnkxA6Cte1JsnKfzhoIZ+lWaKaUe+pxgcOguVuHmGXU57fHH+WzOihwuQflXEovkaHuTxx3QcW4nN20YZoxKqHTdav9Bf1ZamD+6ohT3d9ESZWiP8Swr7Jq2ySwT49jyVtZbUmYKYE2P5Vzzz5zyKbFzhzi7UTaAO0iNDmAwpOr9HSBCHR0t94an7LLbs99NOVIJ8r0SKoGCb6yX1uurHXqDOmrORL8y5g/8rjwPAAFGoYP8EecWEp+yQkn/rIMTrBHIhsS32OG756VdZE9utH6mM1MDE3372Yt6Cy435SBV4yMJOKassrEIBjEQrrqSjZj0igR7/LQE0/hquaantNnXo5pGLxa/lXkMxei682bh4B74BOw2RBXgEiyEcZu4gHwkr9+u6dQoe/oK2GOLL50yGTblnhf2tMluvnZsOIcqwLlBPnPeYc6wrB3D7SSwmwVUx1jcDR2jKm6z+FluG1ieli0/GVKMmI9mZeptCxZYTNo8deYbX4u+tFQd5Xb9tqXtc5Jot45RvqjY/Gmj/oVIZqW0k3HiUtSfOsvfgqsbhRIm9AhUE59cMgPGEWqH3/omk0mT6D5J/MuOt7ZbX1fq+GdWCH/C2Gg3iRRFQsWt7nGFYmy54T/Y8YYY="
